
ifeq ($(MAKECMDGOALS),)
# Set default target for CI environments:
ifeq ($(ENV),development)
DEFAULT ?= 
endif
ifeq ($(ENV),testing)
DEFAULT ?= 
endif
ifeq ($(ENV),production)
DEFAULT ?= 
endif
endif

