
ifeq ($(MAKECMDGOALS),)
# Set default target for CI environments:
ifeq ($(ENV_NAME),development)
DEFAULT ?= 
endif
ifeq ($(ENV_NAME),testing)
DEFAULT ?= 
endif
ifeq ($(ENV_NAME),production)
DEFAULT ?= 
endif
endif

